# https://github.com/helm/chart-testing/blob/main/pkg/config/test_config.yaml
chart-dirs:
  - xomodo
chart-repos:
  - xomodo=https://xomodo.github.io/helm-charts
check-version-increment: true
debug: true
remote: origin
target-branch: main
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
