# See https://github.com/helm/chart-testing#configuration
# https://github.com/helm/chart-testing/blob/main/pkg/config/test_config.yaml

remote: origin
target-branch: main
check-version-increment: true
validate-maintainers: false
validate-chart-schema: false
validate-yaml: true
skip-missing-values: true
#upgrade: true
helm-extra-args: --timeout 600s
helm-lint-extra-args: --quiet
#namespace: default
release-label: release
skip-clean-up: true
chart-dirs:
  - charts
chart-repos:
  - atrakic=https://atrakic.github.io/helm-charts
exclude-deprecated: true
excluded-charts:
  - ingress-nginx
  - argo-cd
