# Default values for kube-prometheus-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
kube-prometheus-stack:
  ## https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  grafana:
    ingres:
      enabled: true
      annotations:
        ingressClassName: "nginx"
        pathType: ImplementationSpecific
    hosts:
      - grafana.localhost.nip.io
    grafana.ini:
      analytics:
        check_for_updates: false
    additionalDataSources:
      - name: Loki
        type: loki
        # isDefault: false
        # access: proxy
        url: http://loki.svc.cluster.local:3100
  prometheus:
    ingres:
      enabled: true
      annotations:
        ingressClassName: "nginx"
        pathType: ImplementationSpecific
    hosts:
      - prometheus.localhost.nip.io
