apiVersion: v2
name: argocd-apps
description: A Helm chart for managing Argo CD Applications
type: application
version: 0.1.6
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argocd
  - gitops

# dependencies:
#  - name: argo-cd
#    version: 7.5.2
#    repository: https://argoproj.github.io/argo-helm
