# Default values for infra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

infra:
  project: default
  namespace: argocd
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/atrakic/argocd-app-of-apps.git
    targetRevision: HEAD

bootstrap:
  repoURL: 'https://atrakic.github.io/helm-charts'
  domain: argo.local

certManager:
  chart: cert-manager
  enabled: true
  namespace: cert-manager
  helm:
    parameters:
      - name: installCRDs
        value: 'true'
      - name: prometheus.servicemonitor.enabled
        value: 'false'
      - name: prometheus.servicemonitor.honorLabels
        value: 'true'

nginx:
  chart: ingress-nginx
  enabled: true
  namespace: ingress-nginx
  helm:
    parameters: []

monitoring:
  chart: kube-prometheus-stack
  enabled: true
  namespace: monitoring
  helm:
    parameters: []

## https://github.com/prometheus-community/helm-charts/tree/kube-prometheus-stack-67.2.0/charts/kube-prometheus-stack/charts/crds/crds
monitoringCrds:
  chart: kube-prometheus-stack-crds
  repoURL: 'https://github.com/prometheus-community/helm-charts.git'
  enabled: true
  namespace: monitoring
  targetRevision: kube-prometheus-stack-67.2.0
  path: charts/kube-prometheus-stack/charts/crds/crds
  helm:
    parameters: []

storage:
  enabled: true
  helm:
    parameters:
      - name: rbac.create
        value: "true"
      - name: storageClass.defaultClass
        value: "true"
    values: |
      storage:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        size: 1Gi

# TODO: disabled ###
logging:
  chart: loki-stack
  repoURL: 'https://grafana.github.io/helm-charts'
  enabled: false
  namespace: monitoring
  targetRevision: 2.10.1
  helm:
    parameters: []

k8spacket:
  chart: k8spacket
  repoURL: 'https://k8spacket.github.io/k8spacket-helm-chart'
  enabled: false
  namespace: k8spacket
  targetRevision: v1.0.0
  helm:
    parameters: []
