controller:
  # watchIngressWithoutClass: true
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
  metrics:
    enabled: true
  defaultBackend:
    enabled: true
    image: ghcr.io/atrakic/go-static-site:latest
