NS ?= $(shell basename $$PWD)
CHART ?= $(shell basename $$PWD)
URL ?= $(shell awk '/repository:/ {print $$2}' Chart.yaml)

all:
	helm dependency build --skip-refresh
	helm template --debug .

install:
	helm upgrade --install --cleanup-on-fail --create-namespace $(CHART) -n $(NS) .

status:
	helm get all $(CHART) -n $(NS)

uninstall:
	helm uninstall $(CHART) -n $(NS)

debug:
	helm show values $(CHART) --repo $(URL)
