{{- if .Values.nginx.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.nginx.chart }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.nginx.namespace }}
    server: {{ .Values.infra.destination.server }}
  project: {{ .Values.infra.project }}
  source:
    chart: {{ .Values.nginx.chart }}
    repoURL: {{ .Values.nginx.repoURL }}
    targetRevision: {{ .Values.nginx.targetRevision }}
    helm:
      values: |
        controller:
          defaultBackend:
            enabled: true
            image: ghcr.io/atrakic/go-static-site:latest
      parameters: {{ .Values.nginx.parameters | toYaml | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
