apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-static-site
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.infra.project }}
  source:
    chart: go-static-site
    repoURL: 'https://github.com/atrakic/go-static-site'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: go-static-site
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
