{{- if .Values.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.certManager.chart }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.infra.project }}
  destination:
    server: {{ .Values.infra.destination.server }}
    namespace: {{ .Values.certManager.namespace }}
  source:
    chart: {{ .Values.certManager.chart }}
    repoURL: {{ .Values.certManager.repoURL }}
    targetRevision: {{ .Values.certManager.targetRevision }}
    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters: {{ .Values.certManager.helm.parameters | toYaml | nindent 8 }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}
