{{- if .Values.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.certManager.chart }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.infra.project }}
  destination:
    server: {{ .Values.infra.destination.server | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.certManager.namespace | default "cert-manager" }}
  source:
    chart: {{ .Values.certManager.chart | default "cert-manager" }}
    repoURL: 'https://atrakic.github.io/helm-charts'
    targetRevision: HEAD
    path: ./upstream/cert-manager
    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters: {{ .Values.certManager.helm.parameters | toYaml | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
