{{- if .Values.nginx.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.nginx.chart }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.infra.project }}
  destination:
    server: {{ .Values.infra.destination.server | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.nginx.namespace | default "ingress-nginx" }}
  source:
    chart: {{ .Values.nginx.chart | default "ingress-nginx" }}
    repoURL: 'https://atrakic.github.io/helm-charts'
    targetRevision: HEAD
    path: ./upstream/ingress-nginx
    helm:
      parameters: {{ .Values.nginx.parameters | toYaml | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
