apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.monitoringCrds.chart }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # should be lower then monitoring chart
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.infra.project | default "default" }}
  destination:
    server: {{ .Values.infra.destination.server | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.monitoringCrds.namespace | default "monitoring" }}
  source:
    repoURL: {{ .Values.monitoringCrds.repoURL }}
    path: {{ .Values.monitoringCrds.path }}
    targetRevision: {{ .Values.monitoringCrds.targetRevision }}
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true # recreate on each version bumps
    automated:
      prune: true
      selfHeal: true
