apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: {{ .Values.infra.project | default "default" }}
  destination:
    namespace: kube-system
    server: {{ .Values.infra.destination.server | default "https://kubernetes.default.svc" }}
  source:
    chart: metrics-server
    repoURL: https://atrakic.github.io/helm-charts
    path: ./upstream/monitoring/metrics-server
    targetRevision: HEAD
    helm:
      parameters:
        - name: metrics.enabled
          value: "true"
  syncPolicy:
    automated:
      selfHeal: true
