apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.infra.destination.server }}
  project: {{ .Values.infra.project }}
  source:
    chart: metrics-server
    repoURL: https://atrakic.github.io/helm-charts
    # Uses path instead of chart so we can follow this commit
    path: ./upstream/metrics-server
    targetRevision: HEAD
    helm:
      parameters:
        - name: metrics.enabled
          value: true
  syncPolicy:
    automated:
      selfHeal: true
