{{- if .Values.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.certManager.chart }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.infra.destination.server }}
    namespace: {{ .Values.certManager.namespace }}
  project: {{ .Values.infra.project }}
  source:
    chart: {{ .Values.certManager.chart }}
    repoURL: {{ .Values.certManager.repoURL }}
    targetRevision: {{ .Values.certManager.targetRevision }}
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
        - name: prometheus.servicemonitor.enabled
          value: 'false'
        - name: prometheus.servicemonitor.honorLabels
          value: 'true'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}
