{{- if .Values.k8spacket.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.k8spacket.chart }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.infra.project }}
  source:
    repoURL: {{ .Values.k8spacket.repoURL }}
    targetRevision: {{ .Values.k8spacket.targetRevision }}
    #helm:
    #  parameters: {}
    chart: {{ .Values.k8spacket.chart }}
  destination:
    server: {{ .Values.infra.destination.server }}
    namespace: {{ .Values.k8spacket.namespace }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}
