cert-manager:
  extraArgs:
  - --enable-certificate-owner-ref=true
  installCRDs: true
  serviceAccount:
    create: false
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      honorLabels: true
