apiVersion: v2
name: promtail
description: A Helm chart for Promtail
type: application
version: 0.0.0
dependencies:
  - name: promtail
    version: 6.3.0
    repository: https://grafana.github.io/helm-charts
