# Default values for containerssh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: NodePort
  # type: LoadBalancer

ssh:
  banner: "Welcome to ContainerSSH!\n"
  hostkeys:
    - /var/secrets/ssh_host_rsa_key

log:
  level: debug

auth:
  url: "http://authconfig:8080"

configserver:
  url: "http://authconfig:8080/config"
