apiVersion: v2
name: ingress-nginx
description: A Helm chart for Nginx Ingress Controller
type: application
version: 0.0.0
dependencies:
- name: ingress-nginx
  version: 4.1.4
  repository: https://kubernetes.github.io/ingress-nginx
