name: Sync GH-Pages
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'
jobs:
  build:
    permissions:
      contents: write # for git push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - run: |
          echo -e "User-Agent: *\nDisallow: /" > robots.txt
          echo -e "theme: jekyll-theme-cayman" > _config.yml
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md robots.txt _config.yml
          git commit --signoff -m "Sync README from main"
          git push
